// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUt4CUhwCTP-DAiiEDC2ZAptl6NYLxxAM',
    appId: '1:446836888023:web:42bebd02da4130573fbb92',
    messagingSenderId: '446836888023',
    projectId: 'stusama-e96bb',
    authDomain: 'stusama-e96bb.firebaseapp.com',
    storageBucket: 'stusama-e96bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFSVOF8CTRUu9qsO0Hc4ZSOWRC9FLK7qw',
    appId: '1:446836888023:android:7d17b1fcfe5a15db3fbb92',
    messagingSenderId: '446836888023',
    projectId: 'stusama-e96bb',
    storageBucket: 'stusama-e96bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2RZzMdONkZbm3ZHS6JmnFBRp2jrw6oRM',
    appId: '1:446836888023:ios:3c26e2cba4a297b33fbb92',
    messagingSenderId: '446836888023',
    projectId: 'stusama-e96bb',
    storageBucket: 'stusama-e96bb.appspot.com',
    iosBundleId: 'com.example.tugasRancang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2RZzMdONkZbm3ZHS6JmnFBRp2jrw6oRM',
    appId: '1:446836888023:ios:9064fc408ef975193fbb92',
    messagingSenderId: '446836888023',
    projectId: 'stusama-e96bb',
    storageBucket: 'stusama-e96bb.appspot.com',
    iosBundleId: 'com.example.tugasRancang.RunnerTests',
  );
}
